/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1p2_felipegarcia;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author felip
 */
public class Login extends javax.swing.JFrame {
    Random r = new Random();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        players.add(new Jugador("Lechuga", 1, "contraseña"));
        players.add(new Jugador("Loco Bryan", 2, "contraseña"));
        players.add(new Jugador("Dr. Nuila", 3, "contraseña"));
        
        letras.add("a");
        letras.add("b");
        letras.add("c");
        letras.add("d");
        letras.add("e");
        letras.add("f");
        letras.add("j");
        letras.add("h");
        letras.add("i");
        letras.add("j");
        letras.add("k");
        letras.add("l");
        letras.add("m");
        letras.add("n");
        letras.add("ñ");
        letras.add("o");
        letras.add("p");
        letras.add("q");
        letras.add("r");
        letras.add("s");
        letras.add("t");
        letras.add("u");
        letras.add("v");
        letras.add("w");
        letras.add("x");
        letras.add("y");
        letras.add("z");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Juego = new javax.swing.JFrame();
        BG2 = new javax.swing.JPanel();
        J_Opciones = new javax.swing.JTabbedPane();
        J_Selec = new javax.swing.JLabel();
        J_Play = new javax.swing.JLabel();
        J_Make = new javax.swing.JLabel();
        J_BG = new javax.swing.JLabel();
        BG = new javax.swing.JPanel();
        Log_txt = new javax.swing.JLabel();
        Log_logo = new javax.swing.JLabel();
        Log_Usrtxt = new javax.swing.JLabel();
        Log_Passtxt = new javax.swing.JLabel();
        Log_Usrinsert = new javax.swing.JTextField();
        Log_Passinsert = new javax.swing.JPasswordField();
        Log_In = new javax.swing.JButton();
        Log_Cre = new javax.swing.JButton();
        Log_BG = new javax.swing.JLabel();

        Juego.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Juego.setTitle("APEX LEGENDS");
        Juego.setPreferredSize(new java.awt.Dimension(610, 600));
        Juego.setResizable(false);

        BG2.setBackground(new java.awt.Color(255, 255, 255));
        BG2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        J_Opciones.setToolTipText("");
        J_Opciones.setName(""); // NOI18N

        J_Selec.setText("jLabel1");
        J_Opciones.addTab("Seleccionar", J_Selec);

        J_Play.setText("jLabel2");
        J_Opciones.addTab("Jugar", J_Play);

        J_Make.setText("jLabel3");
        J_Opciones.addTab("Crear Personaje | Crear Arma", J_Make);

        BG2.add(J_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));
        J_Opciones.getAccessibleContext().setAccessibleName("Crear Personaje");

        J_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/D8ZLsIuUYAA2on9.jpg"))); // NOI18N
        BG2.add(J_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 650, 780));
        J_BG.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout JuegoLayout = new javax.swing.GroupLayout(Juego.getContentPane());
        Juego.getContentPane().setLayout(JuegoLayout);
        JuegoLayout.setHorizontalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JuegoLayout.setVerticalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APEX LEGENDS");
        setLocationByPlatform(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setMinimumSize(new java.awt.Dimension(600, 560));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Log_txt.setBackground(new java.awt.Color(0, 0, 0));
        Log_txt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Log_txt.setForeground(new java.awt.Color(0, 0, 0));
        Log_txt.setText("LOGIN");
        BG.add(Log_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        Log_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/apex-logo-F74B0C9FCD-seeklogo.com.png"))); // NOI18N
        BG.add(Log_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 310, 250));

        Log_Usrtxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Log_Usrtxt.setForeground(new java.awt.Color(0, 0, 0));
        Log_Usrtxt.setText("NOMBRE DE USUARIO: ");
        BG.add(Log_Usrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        Log_Passtxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Log_Passtxt.setForeground(new java.awt.Color(0, 0, 0));
        Log_Passtxt.setText("CONTRASEÑA              :");
        BG.add(Log_Passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 250, -1));

        Log_Usrinsert.setBackground(new java.awt.Color(153, 0, 0));
        Log_Usrinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_UsrinsertActionPerformed(evt);
            }
        });
        BG.add(Log_Usrinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 310, 30));

        Log_Passinsert.setBackground(new java.awt.Color(153, 0, 0));
        BG.add(Log_Passinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 310, 30));

        Log_In.setBackground(new java.awt.Color(204, 102, 0));
        Log_In.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Log_In.setForeground(new java.awt.Color(0, 0, 0));
        Log_In.setText("INICIAR SESION");
        Log_In.setActionCommand("INICIAR SESION");
        Log_In.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Log_In.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_InMouseClicked(evt);
            }
        });
        Log_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_InActionPerformed(evt);
            }
        });
        BG.add(Log_In, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 220, 50));

        Log_Cre.setBackground(new java.awt.Color(204, 102, 0));
        Log_Cre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Log_Cre.setForeground(new java.awt.Color(0, 0, 0));
        Log_Cre.setText("CREAR USUARIO");
        Log_Cre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Log_Cre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_CreMouseClicked(evt);
            }
        });
        Log_Cre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_CreActionPerformed(evt);
            }
        });
        BG.add(Log_Cre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, -1, 50));

        Log_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/D8ZLsIuUYAA2on9.jpg"))); // NOI18N
        BG.add(Log_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 555, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Log_UsrinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_UsrinsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Log_UsrinsertActionPerformed

    private void Log_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_InActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Log_InActionPerformed

    private void Log_InMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_InMouseClicked
        
        String Nombre = Log_Usrinsert.getText();
        String Contraseña = Log_Passinsert.getText();
        int temp = 0;
        
        for (int i = 0; i < players.size(); i++) {
            if(Nombre.equals(players.get(i).getUsername())){
                temp = i;
                i = 1001;
            }
        }
        if(Contraseña.equals(players.get(temp).getPassword())){
        JOptionPane.showMessageDialog(this, "Sesion iniciada correctamente");
        Juego.pack();
        Juego.setLocationRelativeTo(this);
        Juego.setAlwaysOnTop(true);
        Juego.setVisible(true);
      }else{
            JOptionPane.showMessageDialog(this, "Intente denuevo");
        }
    }//GEN-LAST:event_Log_InMouseClicked

    private void Log_CreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_CreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Log_CreActionPerformed

    private void Log_CreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_CreMouseClicked
        // TODO add your handling code here:
        
        String Nombre = Log_Usrinsert.getText();
        int ID;
        String Contraseña = Log_Passinsert.getText();;
        
        if(Nombre.equals("") || Contraseña.equals("")){
            JOptionPane.showMessageDialog(this, "Por Favor Ingrese datos");
        }else{
            ID = 1+r.nextInt(1000);
            for (int i = 0; i < players.size(); i++) {
                if(ID == (players.get(i).getID())){
                    ID = 1+r.nextInt(1000);
                    i = 0;
                }
            }
             Jugador Ply = new Jugador(Nombre, ID, Contraseña);
             players.add(Ply);
             JOptionPane.showMessageDialog(this, "Usuario Creado Correctamente");
        }
    }//GEN-LAST:event_Log_CreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    ArrayList<Jugador> players = new ArrayList();
    ArrayList<String> letras = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BG2;
    private javax.swing.JLabel J_BG;
    private javax.swing.JLabel J_Make;
    private javax.swing.JTabbedPane J_Opciones;
    private javax.swing.JLabel J_Play;
    private javax.swing.JLabel J_Selec;
    private javax.swing.JFrame Juego;
    private javax.swing.JLabel Log_BG;
    private javax.swing.JButton Log_Cre;
    private javax.swing.JButton Log_In;
    private javax.swing.JPasswordField Log_Passinsert;
    private javax.swing.JLabel Log_Passtxt;
    private javax.swing.JTextField Log_Usrinsert;
    private javax.swing.JLabel Log_Usrtxt;
    private javax.swing.JLabel Log_logo;
    private javax.swing.JLabel Log_txt;
    // End of variables declaration//GEN-END:variables
}
