/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1p2_felipegarcia;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author felip
 */
public class Login extends javax.swing.JFrame {
    Random r = new Random();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        weapons.add(new Armas("FlatLine", 10, 80));
        weapons.add(new Armas("Carabina", 15, 90));
        weapons.add(new Armas("PeaceFinder", 30, 40));
        
        characters.add(new Personajes("LifeLine", 100, 50, weapons.get(0), "Medico"));
        characters.add(new Personajes("Vantage", 100, 50, weapons.get(2), "Rastreador"));
        characters.add(new Personajes("Gibby", 125, 75, weapons.get(1), "Medico"));
        
        players.add(new Jugador("Lechuga", 1, "contraseña", characters.get(0)));
        players.add(new Jugador("Loco Bryan", 2, "contraseña", characters.get(1)));
        players.add(new Jugador("Dr. Nuila", 3, "contraseña", characters.get(2)));
        
        letras.add("a");
        letras.add("b");
        letras.add("c");
        letras.add("d");
        letras.add("e");
        letras.add("f");
        letras.add("j");
        letras.add("h");
        letras.add("i");
        letras.add("j");
        letras.add("k");
        letras.add("l");
        letras.add("m");
        letras.add("n");
        letras.add("ñ");
        letras.add("o");
        letras.add("p");
        letras.add("q");
        letras.add("r");
        letras.add("s");
        letras.add("t");
        letras.add("u");
        letras.add("v");
        letras.add("w");
        letras.add("x");
        letras.add("y");
        letras.add("z");
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) J_S_Charlist.getModel();
        modelo.addElement(characters.get(0));
        modelo.addElement(characters.get(1));
        modelo.addElement(characters.get(2));
        
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) J_M_Wpnlist.getModel();
        modelo2.addElement(weapons.get(0));
        modelo2.addElement(weapons.get(1));
        modelo2.addElement(weapons.get(2));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Juego = new javax.swing.JFrame();
        BG2 = new javax.swing.JPanel();
        J_Opciones = new javax.swing.JTabbedPane();
        J_Select = new javax.swing.JPanel();
        J_S_Charlist = new javax.swing.JComboBox<>();
        J_S_TxtS = new javax.swing.JLabel();
        J_S_Selec = new javax.swing.JButton();
        J_Play = new javax.swing.JPanel();
        J_P_Start = new javax.swing.JButton();
        J_P_Log = new javax.swing.JScrollPane();
        J_P_Game = new javax.swing.JTextArea();
        J_P_Player = new javax.swing.JTextField();
        J_P_Attack = new javax.swing.JButton();
        J_Make = new javax.swing.JPanel();
        J_M_txtN = new javax.swing.JLabel();
        J_M_Name = new javax.swing.JTextField();
        J_M_txtV = new javax.swing.JLabel();
        J_M_Vida = new javax.swing.JTextField();
        J_M_txtT = new javax.swing.JLabel();
        J_M_Typlist = new javax.swing.JComboBox<>();
        J_M_txtE = new javax.swing.JLabel();
        J_M_Shield = new javax.swing.JTextField();
        J_M_txtE1 = new javax.swing.JLabel();
        J_M_Wpnlist = new javax.swing.JComboBox<>();
        J_M_txtN2 = new javax.swing.JLabel();
        J_M_Name2 = new javax.swing.JTextField();
        J_M_txtP = new javax.swing.JLabel();
        J_M_Preci = new javax.swing.JTextField();
        J_M_txtD = new javax.swing.JLabel();
        J_M_Dmg = new javax.swing.JTextField();
        J_M_CreatC = new javax.swing.JButton();
        J_M_CreatC1 = new javax.swing.JButton();
        J_BG = new javax.swing.JLabel();
        BG = new javax.swing.JPanel();
        Log_txt = new javax.swing.JLabel();
        Log_logo = new javax.swing.JLabel();
        Log_Usrtxt = new javax.swing.JLabel();
        Log_Passtxt = new javax.swing.JLabel();
        Log_Usrinsert = new javax.swing.JTextField();
        Log_Passinsert = new javax.swing.JPasswordField();
        Log_In = new javax.swing.JButton();
        Log_Cre = new javax.swing.JButton();
        Log_BG = new javax.swing.JLabel();

        Juego.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Juego.setTitle("APEX LEGENDS");
        Juego.setPreferredSize(new java.awt.Dimension(610, 600));
        Juego.setResizable(false);

        BG2.setBackground(new java.awt.Color(255, 255, 255));
        BG2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        J_Opciones.setToolTipText("");
        J_Opciones.setName(""); // NOI18N

        J_Select.setBackground(new java.awt.Color(51, 51, 51));
        J_Select.setForeground(new java.awt.Color(255, 255, 255));
        J_Select.setToolTipText("");

        J_S_Charlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_S_CharlistActionPerformed(evt);
            }
        });

        J_S_TxtS.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        J_S_TxtS.setForeground(new java.awt.Color(255, 255, 255));
        J_S_TxtS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        J_S_TxtS.setText("SELECCIONE UN PERSONJE");

        J_S_Selec.setBackground(new java.awt.Color(153, 153, 153));
        J_S_Selec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        J_S_Selec.setForeground(new java.awt.Color(255, 0, 0));
        J_S_Selec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        J_S_Selec.setLabel("SELECCIONAR");
        J_S_Selec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J_S_SelecMouseClicked(evt);
            }
        });
        J_S_Selec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_S_SelecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout J_SelectLayout = new javax.swing.GroupLayout(J_Select);
        J_Select.setLayout(J_SelectLayout);
        J_SelectLayout.setHorizontalGroup(
            J_SelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(J_S_TxtS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(J_SelectLayout.createSequentialGroup()
                .addGroup(J_SelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(J_SelectLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(J_S_Charlist, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(J_SelectLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(J_S_Selec, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        J_SelectLayout.setVerticalGroup(
            J_SelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(J_SelectLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(J_S_TxtS, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(J_S_Charlist, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(J_S_Selec, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        J_Opciones.addTab("Seleccionar", J_Select);

        J_Play.setBackground(new java.awt.Color(51, 51, 51));

        J_P_Start.setBackground(new java.awt.Color(153, 153, 153));
        J_P_Start.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        J_P_Start.setForeground(new java.awt.Color(255, 0, 0));
        J_P_Start.setText("COMENZAR");
        J_P_Start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        J_P_Start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J_P_StartMouseClicked(evt);
            }
        });
        J_P_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_P_StartActionPerformed(evt);
            }
        });

        J_P_Game.setEditable(false);
        J_P_Game.setColumns(20);
        J_P_Game.setRows(5);
        J_P_Log.setViewportView(J_P_Game);

        J_P_Attack.setBackground(new java.awt.Color(153, 153, 153));
        J_P_Attack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        J_P_Attack.setForeground(new java.awt.Color(255, 0, 0));
        J_P_Attack.setText("ATACAR");
        J_P_Attack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        J_P_Attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_P_AttackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout J_PlayLayout = new javax.swing.GroupLayout(J_Play);
        J_Play.setLayout(J_PlayLayout);
        J_PlayLayout.setHorizontalGroup(
            J_PlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(J_PlayLayout.createSequentialGroup()
                .addGroup(J_PlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(J_PlayLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(J_P_Start))
                    .addGroup(J_PlayLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(J_PlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J_P_Log, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(J_PlayLayout.createSequentialGroup()
                                .addComponent(J_P_Player, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(J_P_Attack, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        J_PlayLayout.setVerticalGroup(
            J_PlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(J_PlayLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(J_P_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(J_P_Log, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(J_PlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J_P_Player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J_P_Attack, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        J_Opciones.addTab("Jugar", J_Play);

        J_Make.setBackground(new java.awt.Color(51, 51, 51));

        J_M_txtN.setBackground(new java.awt.Color(255, 255, 255));
        J_M_txtN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        J_M_txtN.setForeground(new java.awt.Color(255, 255, 255));
        J_M_txtN.setText("Nombre");

        J_M_Name.setBackground(new java.awt.Color(204, 204, 204));

        J_M_txtV.setBackground(new java.awt.Color(255, 255, 255));
        J_M_txtV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        J_M_txtV.setForeground(new java.awt.Color(255, 255, 255));
        J_M_txtV.setText("Vida");

        J_M_Vida.setBackground(new java.awt.Color(204, 204, 204));

        J_M_txtT.setBackground(new java.awt.Color(255, 255, 255));
        J_M_txtT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        J_M_txtT.setForeground(new java.awt.Color(255, 255, 255));
        J_M_txtT.setText("Tipo");

        J_M_Typlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medico", "Rastreador", "Fortaleza" }));
        J_M_Typlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_M_TyplistActionPerformed(evt);
            }
        });

        J_M_txtE.setBackground(new java.awt.Color(255, 255, 255));
        J_M_txtE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        J_M_txtE.setForeground(new java.awt.Color(255, 255, 255));
        J_M_txtE.setText("Escudo");

        J_M_Shield.setBackground(new java.awt.Color(204, 204, 204));

        J_M_txtE1.setBackground(new java.awt.Color(255, 255, 255));
        J_M_txtE1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        J_M_txtE1.setForeground(new java.awt.Color(255, 255, 255));
        J_M_txtE1.setText("Arma");

        J_M_Wpnlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_M_WpnlistActionPerformed(evt);
            }
        });

        J_M_txtN2.setBackground(new java.awt.Color(255, 255, 255));
        J_M_txtN2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        J_M_txtN2.setForeground(new java.awt.Color(255, 255, 255));
        J_M_txtN2.setText("Nombre");

        J_M_Name2.setBackground(new java.awt.Color(204, 204, 204));
        J_M_Name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_M_Name2ActionPerformed(evt);
            }
        });

        J_M_txtP.setBackground(new java.awt.Color(255, 255, 255));
        J_M_txtP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        J_M_txtP.setForeground(new java.awt.Color(255, 255, 255));
        J_M_txtP.setText("Precision");

        J_M_Preci.setBackground(new java.awt.Color(204, 204, 204));

        J_M_txtD.setBackground(new java.awt.Color(255, 255, 255));
        J_M_txtD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        J_M_txtD.setForeground(new java.awt.Color(255, 255, 255));
        J_M_txtD.setText("Daño");

        J_M_Dmg.setBackground(new java.awt.Color(204, 204, 204));
        J_M_Dmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_M_DmgActionPerformed(evt);
            }
        });

        J_M_CreatC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        J_M_CreatC.setForeground(new java.awt.Color(255, 0, 0));
        J_M_CreatC.setText("CREAR PERSONAJE");
        J_M_CreatC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        J_M_CreatC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J_M_CreatCMouseClicked(evt);
            }
        });
        J_M_CreatC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_M_CreatCActionPerformed(evt);
            }
        });

        J_M_CreatC1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        J_M_CreatC1.setForeground(new java.awt.Color(255, 0, 0));
        J_M_CreatC1.setText("CREAR ARMA");
        J_M_CreatC1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        J_M_CreatC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J_M_CreatC1MouseClicked(evt);
            }
        });
        J_M_CreatC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_M_CreatC1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout J_MakeLayout = new javax.swing.GroupLayout(J_Make);
        J_Make.setLayout(J_MakeLayout);
        J_MakeLayout.setHorizontalGroup(
            J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(J_MakeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(J_M_txtD)
                    .addGroup(J_MakeLayout.createSequentialGroup()
                        .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J_M_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(J_M_txtN)
                            .addComponent(J_M_txtE)
                            .addComponent(J_M_Shield, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J_M_txtE1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(J_MakeLayout.createSequentialGroup()
                                .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(J_M_txtV)
                                    .addComponent(J_M_Vida, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(J_M_Wpnlist, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(J_M_txtT)
                                    .addComponent(J_M_Typlist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(J_M_CreatC, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))))
                    .addGroup(J_MakeLayout.createSequentialGroup()
                        .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J_M_Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(J_M_txtN2))
                        .addGap(51, 51, 51)
                        .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J_M_txtP)
                            .addComponent(J_M_Preci, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(J_MakeLayout.createSequentialGroup()
                        .addComponent(J_M_Dmg, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(J_M_CreatC1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        J_MakeLayout.setVerticalGroup(
            J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(J_MakeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(J_MakeLayout.createSequentialGroup()
                        .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(J_M_txtV)
                            .addComponent(J_M_txtT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(J_M_Vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(J_M_Typlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(J_MakeLayout.createSequentialGroup()
                        .addComponent(J_M_txtN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(J_M_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J_M_txtE)
                    .addComponent(J_M_txtE1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J_M_Shield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J_M_Wpnlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J_M_CreatC))
                .addGap(91, 91, 91)
                .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(J_MakeLayout.createSequentialGroup()
                        .addComponent(J_M_txtP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(J_M_Preci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(J_MakeLayout.createSequentialGroup()
                        .addComponent(J_M_txtN2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(J_M_Name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addComponent(J_M_txtD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(J_MakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J_M_Dmg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J_M_CreatC1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        J_Opciones.addTab("Crear Personaje | Crear Arma", J_Make);

        BG2.add(J_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));
        J_Opciones.getAccessibleContext().setAccessibleName("Crear Personaje");

        J_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/D8ZLsIuUYAA2on9.jpg"))); // NOI18N
        BG2.add(J_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 650, 780));
        J_BG.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout JuegoLayout = new javax.swing.GroupLayout(Juego.getContentPane());
        Juego.getContentPane().setLayout(JuegoLayout);
        JuegoLayout.setHorizontalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JuegoLayout.setVerticalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APEX LEGENDS");
        setLocationByPlatform(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setMinimumSize(new java.awt.Dimension(600, 560));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Log_txt.setBackground(new java.awt.Color(0, 0, 0));
        Log_txt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Log_txt.setForeground(new java.awt.Color(0, 0, 0));
        Log_txt.setText("LOGIN");
        BG.add(Log_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        Log_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/apex-logo-F74B0C9FCD-seeklogo.com.png"))); // NOI18N
        BG.add(Log_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 310, 250));

        Log_Usrtxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Log_Usrtxt.setForeground(new java.awt.Color(0, 0, 0));
        Log_Usrtxt.setText("NOMBRE DE USUARIO: ");
        BG.add(Log_Usrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        Log_Passtxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Log_Passtxt.setForeground(new java.awt.Color(0, 0, 0));
        Log_Passtxt.setText("CONTRASEÑA              :");
        BG.add(Log_Passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 250, -1));

        Log_Usrinsert.setBackground(new java.awt.Color(153, 0, 0));
        Log_Usrinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_UsrinsertActionPerformed(evt);
            }
        });
        BG.add(Log_Usrinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 310, 30));

        Log_Passinsert.setBackground(new java.awt.Color(153, 0, 0));
        BG.add(Log_Passinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 310, 30));

        Log_In.setBackground(new java.awt.Color(204, 102, 0));
        Log_In.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Log_In.setForeground(new java.awt.Color(0, 0, 0));
        Log_In.setText("INICIAR SESION");
        Log_In.setActionCommand("INICIAR SESION");
        Log_In.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Log_In.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_InMouseClicked(evt);
            }
        });
        Log_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_InActionPerformed(evt);
            }
        });
        BG.add(Log_In, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 220, 50));

        Log_Cre.setBackground(new java.awt.Color(204, 102, 0));
        Log_Cre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Log_Cre.setForeground(new java.awt.Color(0, 0, 0));
        Log_Cre.setText("CREAR USUARIO");
        Log_Cre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Log_Cre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_CreMouseClicked(evt);
            }
        });
        Log_Cre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_CreActionPerformed(evt);
            }
        });
        BG.add(Log_Cre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, -1, 50));

        Log_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/D8ZLsIuUYAA2on9.jpg"))); // NOI18N
        BG.add(Log_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 555, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Log_UsrinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_UsrinsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Log_UsrinsertActionPerformed

    private void Log_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_InActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Log_InActionPerformed

    private void Log_InMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_InMouseClicked
        
        String Nombre = Log_Usrinsert.getText();
        String Contraseña = Log_Passinsert.getText();
        int temp = 0;
        
        for (int i = 0; i < players.size(); i++) {
            if(Nombre.equals(players.get(i).getUsername())){
                temp = i;
                i = 1001;
            }
        }
        if(Contraseña.equals(players.get(temp).getPassword())){
        JOptionPane.showMessageDialog(this, "Sesion iniciada correctamente");
        Juego.pack();
        Juego.setLocationRelativeTo(this);
        Juego.setAlwaysOnTop(true);
        Juego.setVisible(true);
      }else{
            JOptionPane.showMessageDialog(this, "Intente denuevo");
        }
    }//GEN-LAST:event_Log_InMouseClicked

    private void Log_CreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_CreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Log_CreActionPerformed

    private void Log_CreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_CreMouseClicked
        // TODO add your handling code here:
        
        String Nombre = Log_Usrinsert.getText();
        int ID;
        String Contraseña = Log_Passinsert.getText();;
        
        if(Nombre.equals("") || Contraseña.equals("")){
            JOptionPane.showMessageDialog(this, "Por Favor Ingrese datos");
        }else{
            ID = 1+r.nextInt(1000);
            for (int i = 0; i < players.size(); i++) {
                if(ID == (players.get(i).getID())){
                    ID = 1+r.nextInt(1000);
                    i = 0;
                }
            }
             Jugador Ply = new Jugador(Nombre, ID, Contraseña);
             players.add(Ply);
             JOptionPane.showMessageDialog(this, "Usuario Creado Correctamente");
        }
    }//GEN-LAST:event_Log_CreMouseClicked

    private void J_S_CharlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_S_CharlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_S_CharlistActionPerformed

    private void J_M_TyplistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_M_TyplistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_M_TyplistActionPerformed

    private void J_M_Name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_M_Name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_M_Name2ActionPerformed

    private void J_M_DmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_M_DmgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_M_DmgActionPerformed

    private void J_S_SelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_S_SelecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_S_SelecActionPerformed

    private void J_M_WpnlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_M_WpnlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_M_WpnlistActionPerformed

    private void J_M_CreatCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_M_CreatCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_M_CreatCActionPerformed

    private void J_M_CreatC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_M_CreatC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_M_CreatC1ActionPerformed

    private void J_M_CreatCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J_M_CreatCMouseClicked
        // TODO add your handling code here:
        String Nombre = J_M_Name.getText();
        String life = J_M_Vida.getText();
        String shield = J_M_Shield.getText();
        
        int Vida  = Integer.parseInt(life);
        int Escudo = Integer.parseInt(shield);
        Armas Arma = (Armas)J_M_Wpnlist.getSelectedItem();
        String Tipo = (String)J_M_Typlist.getSelectedItem();
        
        if(Nombre.equals("") || life.equals("") || shield.equals("")){
            
        }else{
            Personajes p = new Personajes(Nombre, Vida, Escudo, Arma, Tipo);
            characters.add(p);
            
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) J_S_Charlist.getModel();
            modelo.addElement(characters.get(characters.size()-1));
            
            J_M_Name.setText("");
            J_M_Vida.setText("");
            J_M_Shield.setText("");
        }
    }//GEN-LAST:event_J_M_CreatCMouseClicked

    private void J_M_CreatC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J_M_CreatC1MouseClicked
        // TODO add your handling code here:
        
        String Nombre = J_M_Name2.getText();;
        String Damage = J_M_Dmg.getText();;
        String P = J_M_Preci.getText();;
        
        int Daño = Integer.parseInt(Damage);
        int Precision = Integer.parseInt(P);
        
        if(Nombre.equals("") || Damage.equals("") || P.equals("")){
            
        }else{
            Armas a = new Armas(Nombre, Daño, Precision);
            weapons.add(a);
            
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) J_M_Wpnlist.getModel();
            modelo.addElement(weapons.get(weapons.size()-1));
            
            J_M_Name2.setText("");
            J_M_Dmg.setText("");
            J_M_Preci.setText("");
        }
    }//GEN-LAST:event_J_M_CreatC1MouseClicked

    private void J_S_SelecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J_S_SelecMouseClicked
        // TODO add your handling code here:
        Personajes p = (Personajes)J_S_Charlist.getSelectedItem();
        
        players.get(3).setP(p);
    }//GEN-LAST:event_J_S_SelecMouseClicked

    private void J_P_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_P_StartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_P_StartActionPerformed

    private void J_P_AttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_P_AttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_P_AttackActionPerformed

    private void J_P_StartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J_P_StartMouseClicked
        // TODO add your handling code here:
        
        int i = 1;
        while(i > 59){
            String name = "";
            int rndN;
            String rnd;
            
            while(name.length() < 10){
                rndN = 0+r.nextInt(27);
                rnd = letras.get(rndN);
                name += rnd;
            }
            
            int ID = 1+r.nextInt(1000);
            for (int i2 = 0; i < players.size(); i++) {
                if(ID == (players.get(i2).getID())){
                    ID = 1+r.nextInt(1000);
                    i2 = 0;
                }
            }
                
            String pass = "";
            int rndP;
            String rnd2;
            
            while(pass.length() < 10){
                rndP = 0+r.nextInt(27);
                rnd2 = letras.get(rndP);
                name += rnd2;
            }
                
            int perrand = 1+r.nextInt(characters.size() - 1);
            
            Personajes p = characters.get(perrand);
            players.add(new Jugador(name, ID, pass, p));
            i++;
        }
        
        for (int j = 0; j < players.size(); j++) {
            J_P_Game.append(players.get(j).toString());
            System.out.println();
        }
        
    }//GEN-LAST:event_J_P_StartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    ArrayList<Jugador> players = new ArrayList();
    ArrayList<String> letras = new ArrayList();
    ArrayList<Armas> weapons = new ArrayList();
    ArrayList<Personajes> characters = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BG2;
    private javax.swing.JLabel J_BG;
    private javax.swing.JButton J_M_CreatC;
    private javax.swing.JButton J_M_CreatC1;
    private javax.swing.JTextField J_M_Dmg;
    private javax.swing.JTextField J_M_Name;
    private javax.swing.JTextField J_M_Name2;
    private javax.swing.JTextField J_M_Preci;
    private javax.swing.JTextField J_M_Shield;
    private javax.swing.JComboBox<String> J_M_Typlist;
    private javax.swing.JTextField J_M_Vida;
    private javax.swing.JComboBox<String> J_M_Wpnlist;
    private javax.swing.JLabel J_M_txtD;
    private javax.swing.JLabel J_M_txtE;
    private javax.swing.JLabel J_M_txtE1;
    private javax.swing.JLabel J_M_txtN;
    private javax.swing.JLabel J_M_txtN2;
    private javax.swing.JLabel J_M_txtP;
    private javax.swing.JLabel J_M_txtT;
    private javax.swing.JLabel J_M_txtV;
    private javax.swing.JPanel J_Make;
    private javax.swing.JTabbedPane J_Opciones;
    private javax.swing.JButton J_P_Attack;
    private javax.swing.JTextArea J_P_Game;
    private javax.swing.JScrollPane J_P_Log;
    private javax.swing.JTextField J_P_Player;
    private javax.swing.JButton J_P_Start;
    private javax.swing.JPanel J_Play;
    private javax.swing.JComboBox<String> J_S_Charlist;
    private javax.swing.JButton J_S_Selec;
    private javax.swing.JLabel J_S_TxtS;
    private javax.swing.JPanel J_Select;
    private javax.swing.JFrame Juego;
    private javax.swing.JLabel Log_BG;
    private javax.swing.JButton Log_Cre;
    private javax.swing.JButton Log_In;
    private javax.swing.JPasswordField Log_Passinsert;
    private javax.swing.JLabel Log_Passtxt;
    private javax.swing.JTextField Log_Usrinsert;
    private javax.swing.JLabel Log_Usrtxt;
    private javax.swing.JLabel Log_logo;
    private javax.swing.JLabel Log_txt;
    // End of variables declaration//GEN-END:variables
}
